media_entity_flickr.settings:
  type: config_object
  label: 'Media entity Flickr settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for thumbnails'

media.source.flickr:
  type: media.source.field_aware
  label: '"Flickr" media source configuration'

field.formatter.settings.flickr_embed:
  type: mapping
  label: 'Flickr field display format settings'
  mapping:
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
